### ISSUE TITLE
add subdural and epidural ICH to the pipeline

### ISSUE THREAD

**Issue by brandonjnelsonFDA** [bnel1201/PedSilicoICH#23]
See for example https://github.com/brandonjnelsonFDA/PedSilicoICH/blob/4b5d0d878f1243b4856ec08e6d177d07cfbef1b8/CT_dataset_pipeline.py#L98

And discussed in #21 for a consistent signature

@jmweaver-FDA , feel free to push your branch when ready and we can start merging our branches together into master

**Comment by jmweaver-FDA** [comment]
Subdural and epidural ICH code just added as separate code - I think what might work best is an "add_lesion.py" file with functions defined inside for each type - "insert_random_sphere", "insert_dural", etc etc. Will work on potentially merging these files together for cleaner code.

**Comment by brandonjnelsonFDA** [comment]
Great work! Thanks for adding that. I agree having a dedicated add_lesion or lesion_insertion module is a good way to organize things, this was loosely the module structure I had in mind at the beginning (from the [README.rst](https://github.com/brandonjnelsonFDA/PedSilicoICH/blob/master/README.rst)) but as we develop more and have a clearer picture of what makes more sense we should continue to update this organizational structure:
![image](https://github.com/user-attachments/assets/5700b87e-641e-47a7-bbe6-0e6f34a79f64)

I'll leave this issue open till we finish this merger of lesion insertion methods
