### ISSUE TITLE
Add CADt device for evaluation

### ISSUE THREAD

**Issue by brandonjnelsonFDA** [bnel1201/PedSilicoICH#24]
See for example:

https://github.com/SeuTao/RSNA2019_Intracranial-Hemorrhage-Detection

Start by evaluating on the provided real patient data, then adult in silico data to confirm similar performance on in silico data. Then finally introduce pediatric data to assess for age bias

**Comment by jmweaver-FDA** [comment]
Currently working on implementing the [2nd place solution](https://github.com/darraghdog/rsna) due to slightly more straightforward instructions and more well-documented Python environment requirements

Will train the models in order of complexity (see "Model Build") section

**Comment by brandonjnelsonFDA** [comment]
Progress has been made here: https://github.com/jmweaver-FDA/ICH-CADt/blob/main/rsna_secondplace/compare_performance.ipynb

![image](https://github.com/user-attachments/assets/9f6c7e63-ae65-4da2-8562-86dbb8def263)

I'm comfortable closing this issue here unless we want to add any tighter connections between the two repos, say a script clone and calling on functions from the other, or merging them

**Comment by brandonjnelsonFDA** [comment]
Is there any more work to be done for this issue or can we close it @jmweaver-FDA?

You've made great progress here:
![image](https://github.com/user-attachments/assets/252ee849-6f43-4337-a0a1-f4a2645f11f6)

Lately we've been focusing on the synthetic data, if there are any other CADt related issues, perhaps we could start new specific issues

**Comment by jmweaver-FDA** [comment]
I think this can be closed - eventually we can add another issue to train another CADt model or fully train this one (multiple folds, more epochs, etc), but for now we have what we want - a "good enough" CADt model.
