### ISSUE TITLE
strange behavior of mass effect in dural lesions

### ISSUE THREAD

**Issue by brandonjnelsonFDA** [bnel1201/PedSilicoICH#68]
Mass effect is meant to push brain tissue away from the growing lesion, but based on its current impementation this can lead to some irregular behavior such as the lesion pulling tissue towards it, see this example of a lesion exerting more mass_effect:

![381228547-224f9f4b-45db-4733-b453-34f0fbe4d9c7](https://github.com/user-attachments/assets/af8eab90-5666-400c-a5cc-a97833ab4e7f)

I recommend playing around with lesion creation and the different parameters here in the [interactive lesion playground notebook](https://github.com/DIDSR/PedSilicoICH/blob/brandon_dev/notebooks/lesion_playground.ipynb)

Because of this issue, the commits for modifying mass effect strength are in a pull request: https://github.com/DIDSR/PedSilicoICH/pull/66

From the brandon_dev branch, see in particular:

https://github.com/DIDSR/PedSilicoICH/blob/brandon_dev/src/pedsilicoICH/lesion_definition.py#L141C1-L154C79

**Comment by brandonjnelsonFDA** [comment]
While we have closed this issue @DhavalKadia-FDA , when you are ready you can create a new issue for yourself introducing the lesion growing model or your new approach to warping, please reach out if you have any questions or want to discuss

**Comment by DhavalKadia-FDA** [comment]
Yes, Brandon. I am going to start later today, or tomorrow.
