### ISSUE TITLE
Small-volume subdural warping bug

### ISSUE THREAD

**Issue by jmweaver-FDA** [bnel1201/PedSilicoICH#86]
The current version of branch [jayse_dev](https://github.com/DIDSR/PedSilicoICH/tree/jayse_dev) can be used to debug. Use the notebook [recon_test](https://github.com/DIDSR/PedSilicoICH/blob/jayse_dev/notebooks/recon_test.ipynb) (first cell) to run the example. The seed is hard-coded in [lesion_definition](https://github.com/DIDSR/PedSilicoICH/commit/b63c66be3b2af3491a3d111066b4257cf52c73b7#diff-993bea25cbbef3edf72ecd8f71c2e0e0221d0f2a6219436050d3648a4175d68cR63). 

Some examples:
Slice 99 warps without error
![image](https://github.com/user-attachments/assets/a2b59261-f973-4e2d-80bb-c72a0edfbbdd)

Slice 98 features a big splotch:
![image](https://github.com/user-attachments/assets/3c64f55a-743c-4747-ba80-b652c2cae56b)

Slice 75 sees the brain completely warped away leaving just the hemorrhage mask:
![image](https://github.com/user-attachments/assets/346170d2-b695-4bc2-88d4-ba607c8a9474)

The ideal fix prevents all 3 from happening. 

My first course of action would be to change the transform interpolation order to see if that changes anything, in addition to checking the src and dst coordinates. 

Assigning myself but @brandonjnelsonFDA feel free to take a stab at it if you have some downtime.

**Comment by brandonjnelsonFDA** [comment]
Thanks for posting this issue! from my experience, my guess is It's something to do with the source and destination coordinates.

I'll start a branch and let you know if I make any progress

**Comment by brandonjnelsonFDA** [comment]
On the topic of subdural hematoma and mass effect, I'll post your link here so we can keep track of it (probably good in the lab notebook too): https://pmc.ncbi.nlm.nih.gov/articles/PMC4620003/figure/Fig1/

**Comment by brandonjnelsonFDA** [comment]
Thanks for these details, I was able to reproduce with the seed = 926 you provided for the MIDA phantom with 10 mL SDH:

Here's a minimal working example:

```python
from pathlib import Path
from dotenv import load_dotenv

from notebooks.utils import ctshow
from pedsilicoICH.ground_truth_definition.phantoms import MIDA_Head

load_dotenv()
import os

phantom_dir = Path(os.environ['PHANTOM_DIRECTORY'])
mida_path = phantom_dir / 'MIDA_Head_Phantom'
seed = 926

phantom = MIDA_Head(mida_path)
phantom.insert_lesion('subdural', volume=10, intensity=100, mass_effect=True, seed=seed)

ctshow(phantom._phantom[78])
```
![image](https://github.com/user-attachments/assets/6b41dc99-2c5b-47f1-8793-90d351ea3c05)

**Comment by brandonjnelsonFDA** [comment]
These lines are dense, I can follow the code up to here then I get lost:

https://github.com/DIDSR/PedSilicoICH/blob/b63c66be3b2af3491a3d111066b4257cf52c73b7/src/pedsilicoICH/lesion_definition.py#L291-L295

**Comment by brandonjnelsonFDA** [comment]
starting to diagnose here: https://github.com/DIDSR/PedSilicoICH/blob/86-small-volume-subdural-warping-bug/subdural.py

Red are where the coordinates have moved, gray they're the same, sometimes the transform destroys the image like below:
![image](https://github.com/user-attachments/assets/e3bd3cf3-ac63-4e3d-895c-d46e69e02aaa)
Other times it does great:
![image](https://github.com/user-attachments/assets/39e443f3-9fa9-4066-ae2a-8682f3f37777)

**Comment by jmweaver-FDA** [comment]
Fixing and closing this issue was first on my list for today - your examples make me think there may be an issue with the coordinate ordering such that warp lines (i.e. point A-->B) are getting crossed which would impact a simple transform. I can take over and hopefully get it sorted out today. (and add comments to 291-295 to clear up what I'm doing here - short answer is appending the 4 corners of the image to both src and dst to make them anchor points)

**Comment by brandonjnelsonFDA** [comment]
We can discuss during our meeting today, I took a stab at it, I at least feel like I better understand what might be happening and I agree with you on the warp lines crossing somehow.

this function I modified from the scikit image thin splin warp tutorial I found helpful, it generates the plots above with the image overlaid with the ordered points and the difference image:

https://github.com/DIDSR/PedSilicoICH/blob/86-small-volume-subdural-warping-bug/src/pedsilicoICH/lesion_definition.py#L301-L340

**Comment by brandonjnelsonFDA** [comment]
Closed with https://github.com/DIDSR/PedSilicoICH/pull/90, great work!

**Comment by brandonjnelsonFDA** [comment]
Later we can explore more performant and better suited for 3D applications, VITK warping: https://vtk.org/doc/nightly/html/classvtkThinPlateSplineTransform.html
