### ISSUE TITLE
Updated readme for SPIE demo

### ISSUE THREAD

**Issue by brandonjnelsonFDA** [bnel1201/PedSilicoICH#92]
Miguel has offered to make us a public website to show off our tool that will be featured at SPIE, like the [s-synth site](https://didsr.github.io/ssynth-release/)

He needs:

1. readme - TODO - good opportunity to update [our readme](https://github.com/DIDSR/PedSilicoICH/blob/master/README.rst) which hasn't been updated in a while
2. directory of 100 images and a csv with metadata. [This is done here ](https://github.com/DIDSR/PedSilicoICH/blob/demo_for_miguel/for_miguel/make_sample_dataset.py)

Here's an example of the demo dataset produced by the script:
[for_miguel.zip](https://github.com/user-attachments/files/18064907/for_miguel.zip)

**Comment by jmweaver-FDA** [comment]
I'll tackle the readme today - I can also tidy up the dataset I'm currently using in the manuscript to include, if we want to include a second dataset or use it as an alternative to the one you've already compiled.

**Comment by brandonjnelsonFDA** [comment]
Thank you! I have a revised one in the pull request I'm waiting to merge: https://github.com/DIDSR/PedSilicoICH/pull/93

There are no files changed, but it adds the `docs` folder which contains materials for the website, including a mini sample dataset saved as windowed pngs and a revised readme that you can build off of: [docs/README.md](https://github.com/DIDSR/PedSilicoICH/blob/demo_for_miguel/docs/README.md) mostly its simplified and as a parameter table, but still work in progress, feedback, edits, and comments welcomed!

**Comment by brandonjnelsonFDA** [comment]
The readme is much improved and the docs website works when run locally, we can close this issue for now, thanks for your help!

https://github.com/DIDSR/PedSilicoICH?tab=readme-ov-file#view-a-sample-dataset-local-demo
